from .profile import Profile
from .asignacion import Asignacion
from .ciclo_escolar import Ciclo_Escolar
from .curso import Curso
from .estudiante import Estudiante
from .evento import Evento
from .grado import Grado
from .material_clase import Material_Clase
from .nivel import Nivel
from .profesion import Profesion
from .profesor import Profesor
from .rol import Rol
from .seccion import Seccion
from .tarea_estudiante import Tarea_Estudiante
from .tarea import Tarea
