# Generated by Django 2.2.13 on 2021-03-26 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='imagenes_curso')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion asignacion')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo_Escolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='curso')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion curso')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.CharField(blank=True, max_length=30, null=True)),
                ('encargado', models.CharField(blank=True, max_length=100, null=True, verbose_name='encargado')),
                ('telefono_encargado', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion_encargado', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(max_length=50, verbose_name='nivel')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion nivel')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesion', models.CharField(max_length=75, verbose_name='profesion')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion profesion')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, verbose_name='rol')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion rol')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='grado')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=50, verbose_name='tarea')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripcion tarea')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_tarea')),
                ('fecha_entrega', models.DateField(verbose_name='%Y-%M-%D')),
                ('hora_entrega', models.TimeField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_tarea', to='api.Asignacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.CharField(max_length=50)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado_calificacion', models.CharField(blank=True, default='Sin calificar', max_length=50, null=True)),
                ('estado_entrega', models.CharField(blank=True, default='No entregado', max_length=50, null=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_estudiante', to='api.Estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_tareaestudiante', to='api.Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Avatar')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MALE'), (1, 'FEMALE')], null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_profile', to='api.Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesor', to='api.Profile')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesion_profesor', to='api.Profesion')),
            ],
        ),
        migrations.CreateModel(
            name='Material_Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=150, verbose_name='evento')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion material')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_material')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_material', to='api.Asignacion')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='grado')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion grado')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_grado', to='api.Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=50, verbose_name='evento')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripcion evento')),
                ('fecha_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cicloEscolar_evento', to='api.Ciclo_Escolar')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ciclo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_Ciclo_Escolar', to='api.Ciclo_Escolar'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_curso', to='api.Curso'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='estudiante',
            field=models.ManyToManyField(to='api.Estudiante'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_grado', to='api.Grado'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_Profesor', to='api.Profesor'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_seccion', to='api.Seccion'),
        ),
    ]
