from .user import UserViewset
from .estudiante import EstudianteViewset
from .profesion import ProfesionViewset
from .rol import RolViewset
from .ciclo_escolar import CicloEscolarViewset
from .nivel import NivelViewset
from .seccion import SeccionViewset
from .curso import CursoViewset
from .grado import GradoViewset
from .profesor import ProfesorViewset
from .asignacion import AsignacionViewset
from .tarea import TareaViewset
from .material import MaterialViewset
from .tarea_estudiante import TareaEstudianteViewset
from .evento import EventoViewset